#!/usr/bin/env bash
set -x

exec ./visualizer-test \
  -w 1280 \
  -h 720 \
  -f 30 \
  -r 48000 \
  -c 2 \
  -b 2 \
  -m 5 \
  -n 5\
  -i /tmp/mpd.fifo \
  -o /tmp/test.avi \
  -l example-lua \
  -p $HOME/bg
